/**
 * Copyright © 2023, School CRM Inc. ALL RIGHTS RESERVED.
 *
 * This software is the confidential information of School CRM Inc., and is licensed as
 * restricted rights software. The use,reproduction, or disclosure of this software is subject to
 * restrictions set forth in your license agreement with School CRM.
*/

export const ActionTypes = {
    AUTH_INFO: "AUTH_INFO",
    DISPLAY_TOAST: "DISPLAY_TOAST",
    MARKSHEET_CLASSDATA: "MARKSHEET_CLASSDATA",
    MARKSHEET_STUDENTS: "MARKSHEET_STUDENTS",
    MENU_ITEM: "MENU_ITEM",
    SET_LISTING_AMENITIES: "SET_LISTING_AMENITIES",
    SET_All_AMENITIES: "SET_All_AMENITIES",
    SET_BUSES: "SET_BUSES",
    SET_All_CLASSES: "SET_All_CLASSES",
    SET_LISTING_CLASSES: "SET_LISTING_CLASSES",
    SET_SCHOOL_CLASSES: "SET_SCHOOL_CLASSES",
    SET_TEACHER_CLASSES: "SET_TEACHER_CLASSES",
    SET_MARKSHEETS: "SET_MARKSHEETS",
    SET_All_SECTIONS: "SET_All_SECTIONS",
    SET_LISTING_SECTIONS: "SET_LISTING_SECTIONS",
    SET_SCHOOL_SECTIONS: "SET_SCHOOL_SECTIONS",
    SET_TEACHER_SECTIONS: "SET_TEACHER_SECTIONS",
    SET_ALL_SCHOOLS: "SET_ALL_SCHOOLS",
    SET_LISTING_SCHOOLS: "SET_LISTING_SCHOOLS",
    SET_SCHOOL_DURATIONS: "SET_SCHOOL_DURATIONS",
    SET_LISTING_SCHOOL_HOUSES: "SET_LISTING_SCHOOL_HOUSES",
    SET_TIME_TABLES: "SET_TIME_TABLES",
    SET_STUDENTS: "SET_STUDENTS",
    SET_ALL_STUDENTS: "SET_ALL_STUDENTS",
    SET_ALL_SUBJECTS: "SET_ALL_SUBJECTS",
    SET_LISTING_SUBJECTS: "SET_LISTING_SUBJECTS",
    SET_SCHOOL_SUBJECTS: "SET_SCHOOL_SUBJECTS",
    SET_TEACHER_SUBJECTS: "SET_TEACHER_SUBJECTS",
    SET_SUBJECT_SUBJECTS: "SET_SUBJECT_SUBJECTS",
    SET_TEACHERS: "SET_TEACHERS",
    SET_ALL_TEACHERS: "SET_ALL_TEACHERS",
    SET_USERS: "SET_USERS",
    SET_EMPLOYEES: "SET_EMPLOYEES",
    SET_GENERATE_ID_CARD: "SET_GENERATE_ID_CARD",
    SET_NOTICES: "SET_NOTICES",
    SET_HOLIDAYS: "SET_HOLIDAYS",
    SET_HOMEWORKS: "SET_HOMEWORKS",
    SET_PAYMENTS: "SET_PAYMENTS",
    SET_LISTING_PAYMENT_METHODS: "SET_LISTING_PAYMENT_METHODS",
    SET_All_PAYMENT_METHODS: "SET_All_PAYMENT_METHODS",
    SET_LISTING_USER_ROLES: "SET_LISTING_USER_ROLES",
    SET_ALL_USER_ROLES: "SET_ALL_USER_ROLES",
    REGISTER_USER: "REGISTER_USER"
};
